"""Core types and models for the Moodle AI Assistant."""

from typing import Annotated, List, Dict, Any, Optional
from typing_extensions import TypedDict
from langchain_core.documents.base import Document
from langgraph.graph import MessagesState


class ConversationState(MessagesState):
    """State management for conversation flow.

    This class manages the context and history of the conversation.
    It's a subclassed `MessagesState` with additional `context` and `video_metadata` management capabilities.
    """

    ##TODO Refactor to suggest an appropriate reducer to update context
    ## context: Annotated[List[Document], reducer]
    context: List[Document]
    video_metadata: Optional[Dict[str, Any]]
    hypothetical_document: Optional[str]   # HyDE-generated hypothetical document (legacy)
    enhanced_query: Optional[str]          # [LEGACY] Enhanced query from query enhancement node
    query_variants: List[str]              # Generated by multi_query node
    route: Optional[str]                   # "rag" | "llm_only" — set by route_query node
    selected_domain: Optional[str]         # Domain focus selected by the user (e.g. "Ganterie")
    course_id: Optional[str]              # Moodle course ID — enables per-course collection query
    refined_query: Optional[str]           # PRF-reformulated query (set by refine_query_prf node)
